version: "3.1"
services:
  web:
    build: .
    volumes:
      - .:/srv:Z
      - /srv/node_modules
    ports:
      - "3000:3000"
  db:
    image: postgres:11
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
