name: Tests

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build the Docker images
        run: docker-compose build
      - name: Initialize database
        run: docker-compose run web bin/initialize.sh
      - name: Run tests
        run: docker-compose run web bin/test.sh --ruby
      - name: Yarn integrity check
        run: docker-compose run web bin/test.sh --yarn-integrity
